# Generated by Django 6.0.6 on 2026-06-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="الاسم")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("استفسار عن الاشتراك", "استفسار عن الاشتراك"),
                            ("ترشيح حالة للدعم", "ترشيح حالة للدعم"),
                            ("اقتراح أو ملاحظة", "اقتراح أو ملاحظة"),
                            ("تطوّع / شراكة", "تطوّع / شراكة"),
                            ("أخرى", "أخرى"),
                        ],
                        max_length=40,
                        verbose_name="الموضوع",
                    ),
                ),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="تمت المعالجة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإرسال"
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة تواصل",
                "verbose_name_plural": "رسائل التواصل",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month_label",
                    models.CharField(
                        help_text="مثال: حزيران ٢٠٢٦",
                        max_length=60,
                        verbose_name="عنوان الدورة",
                    ),
                ),
                (
                    "target_subscribers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد المشتركين المستهدف"
                    ),
                ),
                (
                    "current_subscribers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد المشتركين الحالي"
                    ),
                ),
                (
                    "active_cases",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد الحالات قيد الدعم"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="الدورة الحالية"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "دورة",
                "verbose_name_plural": "الدورات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="السؤال")),
                ("answer", models.TextField(verbose_name="الجواب")),
                (
                    "is_open",
                    models.BooleanField(default=False, verbose_name="مفتوح افتراضياً"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
            ],
            options={
                "verbose_name": "سؤال شائع",
                "verbose_name_plural": "الأسئلة الشائعة",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("hero", "شريط البطل (الرئيسية)"),
                            ("band", "شريط الإحصاءات (الرئيسية)"),
                            ("transparency", "شريط الشفافية (عن المبادرة)"),
                        ],
                        max_length=15,
                        verbose_name="المجموعة",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="مثال: ٨٫٤ مليون أو ١٠٠٪",
                        max_length=40,
                        verbose_name="القيمة",
                    ),
                ),
                ("label", models.CharField(max_length=120, verbose_name="الوصف")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
            ],
            options={
                "verbose_name": "إحصائية",
                "verbose_name_plural": "الإحصاءات",
                "ordering": ["group", "order"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=160, verbose_name="الاسم الكامل"),
                ),
                (
                    "rank",
                    models.CharField(blank=True, max_length=80, verbose_name="الرتبة"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="التشكيل / الوحدة"
                    ),
                ),
                ("phone", models.CharField(max_length=30, verbose_name="رقم الهاتف")),
                (
                    "monthly_amount",
                    models.CharField(
                        choices=[
                            ("١٬٠٠٠ دينار (الأساسية)", "١٬٠٠٠ دينار (الأساسية)"),
                            ("٢٬٠٠٠ دينار", "٢٬٠٠٠ دينار"),
                            ("٥٬٠٠٠ دينار", "٥٬٠٠٠ دينار"),
                            ("مبلغ آخر", "مبلغ آخر"),
                        ],
                        default="١٬٠٠٠ دينار (الأساسية)",
                        max_length=40,
                        verbose_name="المساهمة الشهرية",
                    ),
                ),
                (
                    "consent",
                    models.BooleanField(
                        default=False, verbose_name="الموافقة على الالتزام"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("contacted", "تم التواصل"),
                            ("done", "مكتمل"),
                        ],
                        default="new",
                        max_length=12,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الطلب"),
                ),
            ],
            options={
                "verbose_name": "طلب اشتراك",
                "verbose_name_plural": "طلبات الاشتراك",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=60, unique=True, verbose_name="الاسم"),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("default", "أخضر (افتراضي)"),
                            ("gold", "ذهبي"),
                            ("urgent", "عاجل (أحمر)"),
                            ("done", "مكتملة"),
                        ],
                        default="default",
                        max_length=10,
                        verbose_name="النمط",
                    ),
                ),
            ],
            options={
                "verbose_name": "وسم",
                "verbose_name_plural": "الوسوم",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="العنوان")),
                (
                    "location",
                    models.CharField(blank=True, max_length=120, verbose_name="الموقع"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="cases/", verbose_name="الصورة"
                    ),
                ),
                (
                    "collected_amount",
                    models.BigIntegerField(
                        default=0, verbose_name="المبلغ المجموع (دينار)"
                    ),
                ),
                (
                    "target_amount",
                    models.BigIntegerField(
                        default=0, verbose_name="المبلغ المستهدف (دينار)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "قيد الدعم"), ("done", "مكتملة")],
                        default="active",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                ("is_urgent", models.BooleanField(default=False, verbose_name="عاجلة")),
                (
                    "show_on_home",
                    models.BooleanField(
                        default=False, verbose_name="إظهار في الصفحة الرئيسية"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cases",
                        to="core.tag",
                        verbose_name="الوسوم",
                    ),
                ),
            ],
            options={
                "verbose_name": "حالة",
                "verbose_name_plural": "الحالات",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
