# Generated by Django 6.0.6 on 2026-06-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="سوبر كي العراق",
                        max_length=80,
                        verbose_name="مزوّد المحفظة",
                    ),
                ),
                (
                    "wallet_number",
                    models.CharField(
                        help_text="الرقم الذي يحوّل إليه المتبرّع عبر تطبيق سوبر كي.",
                        max_length=60,
                        verbose_name="رقم المحفظة",
                    ),
                ),
                (
                    "holder_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="اسم صاحب المحفظة"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="تظهر أسفل رقم المحفظة، مثل: يُرجى إرسال الاسم بعد التحويل.",
                        max_length=200,
                        verbose_name="ملاحظة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
            ],
            options={
                "verbose_name": "معلومات التحويل",
                "verbose_name_plural": "معلومات التحويل",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="العنوان")),
                (
                    "location",
                    models.CharField(blank=True, max_length=120, verbose_name="الموقع"),
                ),
                (
                    "visit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الزيارة"
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="سطر مختصر يظهر في البطاقة والصفحة الرئيسية.",
                        max_length=240,
                        verbose_name="مقتطف",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="التفاصيل")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="visits/",
                        verbose_name="الصورة",
                    ),
                ),
                (
                    "show_on_home",
                    models.BooleanField(
                        default=False, verbose_name="إظهار في الصفحة الرئيسية"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
            ],
            options={
                "verbose_name": "زيارة ميدانية",
                "verbose_name_plural": "الزيارات الميدانية",
                "ordering": ["order", "-visit_date", "-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="subscriptionrequest",
            name="rank",
        ),
        migrations.RemoveField(
            model_name="subscriptionrequest",
            name="unit",
        ),
        migrations.AddField(
            model_name="cycle",
            name="amount_collected",
            field=models.BigIntegerField(
                default=0,
                help_text="المبلغ الحقيقي المجموع هذه الدورة بالدينار — يُعرض في الصفحة الرئيسية. مثال: ٧٥٠٠٠٠",
                verbose_name="المبلغ المجموع فعلياً (دينار)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrequest",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="ألغِ التفعيل لإيقاف التذكيرات عن هذا الشخص.",
                verbose_name="مشترك فعّال",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrequest",
            name="last_reminder_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="آخر تذكير"),
        ),
        migrations.AddField(
            model_name="subscriptionrequest",
            name="whatsapp_opt_in",
            field=models.BooleanField(
                default=True, verbose_name="استلام تذكير واتساب الشهري"
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="collected_amount",
            field=models.BigIntegerField(
                default=0,
                help_text="أدخل المبلغ بالدينار كاملاً، مثال: ٣٢٠٠٠٠٠ (٣٫٢ مليون). يُعرض تلقائياً بالملايين.",
                verbose_name="المبلغ المجموع (دينار)",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="target_amount",
            field=models.BigIntegerField(
                default=0,
                help_text="أدخل المبلغ بالدينار كاملاً، مثال: ٥٠٠٠٠٠٠ (٥ مليون).",
                verbose_name="المبلغ المستهدف (دينار)",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionrequest",
            name="consent",
            field=models.BooleanField(default=False, verbose_name="الموافقة"),
        ),
        migrations.AlterField(
            model_name="subscriptionrequest",
            name="monthly_amount",
            field=models.CharField(
                choices=[
                    ("١٬٠٠٠ دينار (الحد الأدنى)", "١٬٠٠٠ دينار (الحد الأدنى)"),
                    ("٢٬٠٠٠ دينار", "٢٬٠٠٠ دينار"),
                    ("٥٬٠٠٠ دينار", "٥٬٠٠٠ دينار"),
                    ("١٠٬٠٠٠ دينار", "١٠٬٠٠٠ دينار"),
                    ("مبلغ آخر", "مبلغ آخر"),
                ],
                default="١٬٠٠٠ دينار (الحد الأدنى)",
                max_length=40,
                verbose_name="المساهمة الشهرية",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionrequest",
            name="phone",
            field=models.CharField(
                help_text="يُفضّل أن يكون مرتبطاً بواتساب لاستلام التذكير الشهري.",
                max_length=30,
                verbose_name="رقم الهاتف (واتساب)",
            ),
        ),
    ]
