# Generated by Django 6.0.6 on 2026-06-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_paymentinfo_visit_remove_subscriptionrequest_rank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinfo",
            name="fallback_phone",
            field=models.CharField(
                blank=True,
                help_text="في حال تعذّر التحويل لرقم المحفظة، يمكن التحويل عبر هذا الرقم.",
                max_length=30,
                verbose_name="رقم الهاتف البديل للتحويل",
            ),
        ),
        migrations.AddField(
            model_name="paymentinfo",
            name="qr_image",
            field=models.ImageField(
                blank=True,
                help_text="صورة رمز الاستجابة السريعة (QR) للتحويل — اختيارية.",
                null=True,
                upload_to="payment/",
                verbose_name="صورة QR للتحويل",
            ),
        ),
    ]
