# Generated by Django 5.2.15 on 2026-07-03 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paymentinfo_fallback_phone_paymentinfo_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='video_file',
            field=models.FileField(blank=True, help_text='ارفع مقطع فيديو (mp4) — اختياري.', null=True, upload_to='cases/videos/', verbose_name='ملف فيديو'),
        ),
        migrations.AddField(
            model_name='case',
            name='video_url',
            field=models.URLField(blank=True, help_text='أو الصق رابط يوتيوب بدلاً من رفع ملف — اختياري.', verbose_name='رابط فيديو'),
        ),
        migrations.AddField(
            model_name='visit',
            name='video_file',
            field=models.FileField(blank=True, help_text='ارفع مقطع فيديو (mp4) — اختياري.', null=True, upload_to='visits/videos/', verbose_name='ملف فيديو'),
        ),
        migrations.AddField(
            model_name='visit',
            name='video_url',
            field=models.URLField(blank=True, help_text='أو الصق رابط يوتيوب بدلاً من رفع ملف — اختياري.', verbose_name='رابط فيديو'),
        ),
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(blank=True, help_text='الصورة التي تظهر على البطاقة. أضف صوراً إضافية من قسم «صور الحالة» أدناه.', null=True, upload_to='cases/', verbose_name='الصورة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='image',
            field=models.ImageField(blank=True, help_text='الصورة التي تظهر على البطاقة. أضف صوراً إضافية من قسم «صور الزيارة» أدناه.', null=True, upload_to='visits/', verbose_name='الصورة الرئيسية'),
        ),
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cases/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=160, verbose_name='تعليق')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.case', verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'صورة حالة',
                'verbose_name_plural': 'صور الحالة',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VisitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='visits/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=160, verbose_name='تعليق')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.visit', verbose_name='الزيارة')),
            ],
            options={
                'verbose_name': 'صورة زيارة',
                'verbose_name_plural': 'صور الزيارة',
                'ordering': ['order', 'id'],
            },
        ),
    ]
